name: GitHub-Profile-3D-Contrib

on:
  schedule:
   - cron: "30 17 * * *" # Runs daily at 12:00 AM MMT (17:30 UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    permissions:
      contents: write # Allows GitHub Action to commit and push the SVG
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: khantpyaehtoo
          PROFILE_NAME: night-green
      - name: Commit & Push changes
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -A .
          git commit -m "generated 3d contribution graph" || exit 0
          git push
